### ISSUE TITLE
Equal voltage levels are not recognized

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/OSMoGrid#395]
```
edu.ie3.datamodel.exceptions.InvalidGridException: There are 17 voltage levels apparent, although only one is expected. Following voltage levels are present: VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}, VoltageLevel{id='mv', nominalVoltage=10 kV}
	at edu.ie3.datamodel.utils.ContainerUtils.determinePredominantVoltLvl(ContainerUtils.java:475)
	at edu.ie3.datamodel.models.input.container.SubGridContainer.<init>(SubGridContainer.java:31)
	at utils.GridConversion$.buildGridContainer(GridConversion.scala:287)
	at edu.ie3.osmogrid.mv.MvGridGeneratorSupport$.buildGrid(MvGridGeneratorSupport.scala:96)
	at edu.ie3.osmogrid.mv.VoronoiCoordinator$.$anonfun$convertingGraphToPSDM$1(VoronoiCoordinator.scala:102)
	at org.apache.pekko.actor.typed.internal.BehaviorImpl$ReceiveBehavior.receive(BehaviorImpl.scala:146)
	at org.apache.pekko.actor.typed.Behavior$.interpret(Behavior.scala:283)
	at org.apache.pekko.actor.typed.Behavior$.interpretMessage(Behavior.scala:239)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:141)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:117)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by staudtMarius** [comment]
This may be resolved by [this](https://github.com/ie3-institute/PowerSystemDataModel/pull/1064).
