### ISSUE TITLE
IllegalArgumentException caused by historic data for ways

### ISSUE THREAD

**Issue by danielfeismann** [ie3-institute/OSMoGrid#422]
```
15:58:15.739 ERROR e.i.osmogrid.guardian.run.RunSupport - Node 268847628 of Way 24737158 is not within our nodes mapping
java.lang.IllegalArgumentException: Node 268847628 of Way 24737158 is not within our nodes mapping
	at utils.OsmoGridUtils$.$anonfun$buildStreetGraph$2(OsmoGridUtils.scala:126)
	at utils.OsmoGridUtils$.$anonfun$buildStreetGraph$2$adapted(OsmoGridUtils.scala:113)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1303)
	at utils.OsmoGridUtils$.$anonfun$buildStreetGraph$1(OsmoGridUtils.scala:113)
	at utils.OsmoGridUtils$.$anonfun$buildStreetGraph$1$adapted(OsmoGridUtils.scala:111)
	at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:2124)
	at scala.collection.immutable.Vector.foreach(Vector.scala:2130)
	at utils.OsmoGridUtils$.buildStreetGraph(OsmoGridUtils.scala:111)
	at edu.ie3.osmogrid.lv.LvCoordinator$.$anonfun$awaitResults$1(LvCoordinator.scala:244)
	at org.apache.pekko.actor.typed.internal.BehaviorImpl$ReceiveBehavior.receive(BehaviorImpl.scala:146)
	at org.apache.pekko.actor.typed.Behavior$.interpret(Behavior.scala:283)
	at org.apache.pekko.actor.typed.Behavior$.interpretMessage(Behavior.scala:239)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:141)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:117)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Only hypothesis, needs to be checked: This may be caused by bounderies that are only partly in the pbf-File and thus couldn't be of type ClosedWay.

Edit: Reason is historic data for ways.

**Comment by danielfeismann** [comment]
Reason for this exception lies in being all versions, also from the past, of the way are considered. See [osm history](https://www.openstreetmap.org/api/0.6/way/486458680/history)

```
<osm version="0.6" generator="CGImap 0.9.2 (2785514 spike-07.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<way id="486458680" visible="true" version="1" changeset="47708870" timestamp="2017-04-12T21:04:23Z" user="herisusa" uid="107703">
<nd ref="268847063"/>
<nd ref="268847628"/>
<nd ref="268847629"/>
<nd ref="268847630"/>
<nd ref="268847631"/>
<nd ref="268847632"/>
<nd ref="268847633"/>
<nd ref="271199701"/>
<nd ref="4790734805"/>
<tag k="highway" v="unclassified"/>
</way>
<way id="486458680" visible="true" version="2" changeset="102048016" timestamp="2021-03-31T10:32:20Z" user="flohoff" uid="34927">
<nd ref="268847063"/>
<nd ref="268847630"/>
<nd ref="268847631"/>
<nd ref="268847632"/>
<nd ref="268847633"/>
<nd ref="271199701"/>
<nd ref="4790734805"/>
<tag k="highway" v="unclassified"/>
</way>
</osm>
```

requires changes in PSU as well: [PSU#466](https://github.com/ie3-institute/PowerSystemUtils/issues/466)

**Comment by danielfeismann** [comment]
Closed, since no longer necessary when using overpass.
